### ISSUE TITLE
Crash when using pyFAMSA with UPGMA (0.3.1)

### ISSUE THREAD

**Issue by davidlougheed** [althonos/pyfamsa#2]
Hello,
I get a crash (segfault) in multiprocessing mode when using pyFAMSA version 0.3.0 OR version 0.3.1:
This only happens after several successful alignments, so I'm not quite sure why.

Edit: actually, this can happen in single-process python application too (albeit with multi-threaded pyFAMSA)

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x7ffffffe04fec984 -> 0xfffffffe04fec984 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x7ffffffe04fec984

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [81554]

VM Region Info: 0xfffffffe04fec984 is not in any region.  Bytes after previous region: 18446638511550286213  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END

Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   _famsa.cpython-310-darwin.so  	       0x12446395c void UPGMA<(Distance)1>::computeTree<false>(float*, int, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int>>>&) + 772
1   _famsa.cpython-310-darwin.so  	       0x124462e0c UPGMA<(Distance)0>::run(std::__1::vector<CSequence*, std::__1::allocator<CSequence*>>&, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int>>>&) + 132
2   _famsa.cpython-310-darwin.so  	       0x124444e28 AbstractTreeGenerator::operator()(std::__1::vector<CSequence*, std::__1::allocator<CSequence*>>&, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int>>>&) + 100
3   _famsa.cpython-310-darwin.so  	       0x12443c650 CFAMSA::ComputeMSA(std::__1::vector<CSequence, std::__1::allocator<CSequence>>&) + 4184
4   _famsa.cpython-310-darwin.so  	       0x12442ab40 __pyx_f_7pyfamsa_6_famsa_7Aligner_align(__pyx_obj_7pyfamsa_6_famsa_Aligner*, _object*, int) + 744
5   _famsa.cpython-310-darwin.so  	       0x124432d30 __pyx_pw_7pyfamsa_6_famsa_7Aligner_5align(_object*, _object* const*, long, _object*) + 428
6   Python                        	       0x104815b70 call_function + 124
7   Python                        	       0x1048120c0 _PyEval_EvalFrameDefault + 30048
8   Python                        	       0x104809c18 _PyEval_Vector + 368
9   Python                        	       0x104815b70 call_function + 124
10  Python                        	       0x10481215c _PyEval_EvalFrameDefault + 30204
11  Python                        	       0x104809c18 _PyEval_Vector + 368
12  Python                        	       0x104803f50 map_next + 180
13  Python                        	       0x104763064 list_extend + 472
14  Python                        	       0x104762ddc list_vectorcall + 96
15  Python                        	       0x104815b70 call_function + 124
16  Python                        	       0x10481215c _PyEval_EvalFrameDefault + 30204
17  Python                        	       0x104809c18 _PyEval_Vector + 368
18  Python                        	       0x1047430d4 PyVectorcall_Call + 176
19  Python                        	       0x1048122e8 _PyEval_EvalFrameDefault + 30600
20  Python                        	       0x104809c18 _PyEval_Vector + 368
21  Python                        	       0x1048122e8 _PyEval_EvalFrameDefault + 30600
22  Python                        	       0x104809c18 _PyEval_Vector + 368
23  Python                        	       0x1048122e8 _PyEval_EvalFrameDefault + 30600
24  Python                        	       0x104809c18 _PyEval_Vector + 368
25  Python                        	       0x104815b70 call_function + 124
26  Python                        	       0x1048120c0 _PyEval_EvalFrameDefault + 30048
27  Python                        	       0x104809c18 _PyEval_Vector + 368
28  Python                        	       0x104815b70 call_function + 124
29  Python                        	       0x1048120c0 _PyEval_EvalFrameDefault + 30048
30  Python                        	       0x104809c18 _PyEval_Vector + 368
31  Python                        	       0x104815b70 call_function + 124
32  Python                        	       0x10481215c _PyEval_EvalFrameDefault + 30204
33  Python                        	       0x104809c18 _PyEval_Vector + 368
34  Python                        	       0x104815b70 call_function + 124
35  Python                        	       0x1048121d8 _PyEval_EvalFrameDefault + 30328
36  Python                        	       0x104809c18 _PyEval_Vector + 368
37  Python                        	       0x104809a94 PyEval_EvalCode + 104
38  Python                        	       0x104855d90 run_eval_code_obj + 84
39  Python                        	       0x104855cf4 run_mod + 112
40  Python                        	       0x104857714 PyRun_StringFlags + 128
41  Python                        	       0x10485764c PyRun_SimpleStringFlags + 64
42  Python                        	       0x10486e754 Py_RunMain + 340
43  Python                        	       0x10486f9f0 Py_BytesMain + 40
44  dyld                          	       0x1929eff28 start + 2236


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000007fffffff   x1: 0x000000007fffffff   x2: 0x000000007fffffff   x3: 0x000000007fffffff
    x4: 0x0000000000000000   x5: 0x1fffffff40000001   x6: 0x1fffffff40000001   x7: 0x0000000000000000
    x8: 0x0000000104b30164   x9: 0x0000000104b37320  x10: 0x000000000000000c  x11: 0x0000000104b373c0
   x12: 0x0000000104b37458  x13: 0x0000000104b300cc  x14: 0x0000000104b30118  x15: 0x0000000000000014
   x16: 0x0000000104b37320  x17: 0x0000000104b30164  x18: 0x0000000000000000  x19: 0x0000000104b30080
   x20: 0x0000000104b37280  x21: 0x3ffffffe80000002  x22: 0x0000000000000014  x23: 0x0000000104fec980
   x24: 0x0000600002aed958  x25: 0x0000000000000014  x26: 0x0000000000000013  x27: 0x000000007fffffff
   x28: 0x00000001065d5db0   fp: 0x000000016ba6c790   lr: 0x6f3e8001244636c4
    sp: 0x000000016ba6c730   pc: 0x000000012446395c cpsr: 0x60001000
   far: 0x7ffffffe04fec984  esr: 0x92000004 (Data Abort) byte read Translation fault
```

**Comment by davidlougheed** [comment]
I also eventually get a crash with the default guide tree method.

**Comment by davidlougheed** [comment]
this is the list of sequences:

```py
['', '', 'TGTGTGTGTGT', 'TGTGTGTGTGT', 'TGTGTGTGTGT', 'TGTGTGTGTGT', '', 'TGTGTGTGTGT', 'TGTGTGTGTGT', 'TGTGTGTGTGT', 'TGTGTGTGTGT', 'TGTGTGTGTGT', '', 'TGTGTGTGTGT', 'TGTGTGTGTGT', '', 'TGTGTGTGTGT', '', '', 'TGTGTGTGTGT']
```

I'm guessing it doesn't like the blank strings

**Comment by althonos** [comment]
Hi @davidlougheed, thanks for the report.

I think FAMSA doesn't support empty strings and that's why it's crashing, when I checked with the FAMSA command line it just discards empty sequences prior to alignment. I will update `Sequence` to raise an exception when given an empty string rather than letting it go inside the FAMSA aligner and segfault.

**Comment by althonos** [comment]
"Fixed" (as in, prevent this from happening again) in `v0.3.2`.

**Comment by davidlougheed** [comment]
@althonos I am still getting this crash occasionally, actually - here's an example of sequences that aren't blank that cause a crash:

```
('ACACACACACACACACACACACACACACACACACA', 'TTTTTG', 'ACACACACACACACACACACACACACACACACACACA', 'ACACACACACACACACACACACACACACACACACACA', 'ACACACACACACACACACACACACACACACA', 'ACACACACACACACACACACACACACACACA')
```
in this case, the glaring thing standing out is that `TTTTTG` shares no chars with any of the other strings...

**Comment by althonos** [comment]
The crashes are coming from the FAMSA code and occuring with both PyFAMSA and the compiled FAMSA, so I opened an issue there.
